### ISSUE TITLE
segmentation fault 

### ISSUE THREAD

**Issue by dao** [status-im/nwaku#977]
I see occasional segfaults from wakunode2. Here is a gdb backtrace of the most recent coredump:

```
#0  rawAlloc__mE4QEVyMvGRVliDWDngZCQ (a=a@entry=0x7fb96e434788, requestedSize=requestedSize@entry=2033)
    at /mnt/c/source/status-im/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/alloc.nim:783
#1  0x0000558a6ca5c3cf in rawNewObj__ehkAaLROrd0Hc9aLROWt1nQ (typ=typ@entry=0x558a6d060200 <strDesc__D0UzA4zsDu5tgpJQ9a9clXPg>, size=size@entry=2017,
    gch=0x7fb96e434720) at /mnt/c/source/status-im/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim:799
#2  0x0000558a6ca5c5fe in newObj (typ=typ@entry=0x558a6d060200 <strDesc__D0UzA4zsDu5tgpJQ9a9clXPg>, size=size@entry=2017)
    at /mnt/c/source/status-im/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim:440
#3  0x0000558a6ca5f136 in rawNewString (space=2000) at /mnt/c/source/status-im/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/sysstr.nim:55
#4  signalHandler (sign=11) at /mnt/c/source/status-im/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim:609
#5  <signal handler called>
#6  _mm_xor_si128 (__B=<error reading variable: Cannot access memory at address 0x7fb96e133004>, __A=...)
    at /usr/lib/gcc/x86_64-linux-gnu/9/include/emmintrin.h:1305
#7  br_aes_x86ni_ctr_run (ctx=<optimized out>, iv=<optimized out>, cc=<optimized out>, data=<optimized out>, len=18446744073598554273)
    at /mnt/c/source/status-im/nim-waku/vendor/nim-bearssl/bearssl/csources/src/symcipher/aes_x86ni_ctr.c:158
#8  0x0000558a6c93a357 in do_ctr (xortag=0x7fff7b98ead0, len=18446744073709551585, data=0x7fb9677580b4, nonce=0x7fb9677580ac, cc=0x7fb967ac3188)
    at /mnt/c/source/status-im/nim-waku/vendor/nim-bearssl/bearssl/csources/src/ssl/ssl_rec_gcm.c:118
#9  gcm_encrypt (cc=0x7fb967ac3188, record_type=21, version=771, data=0x7fb9677580b4, data_len=0x7fff7b98eb30)
    at /mnt/c/source/status-im/nim-waku/vendor/nim-bearssl/bearssl/csources/src/ssl/ssl_rec_gcm.c:206
#10 0x0000558a6c932145 in sendpld_flush (force=0, rc=0x7fb967ac2ed0)
    at /mnt/c/source/status-im/nim-waku/vendor/nim-bearssl/bearssl/csources/src/ssl/ssl_engine.c:851
#11 sendpld_ack (len=<optimized out>, rc=0x7fb967ac2ed0) at /mnt/c/source/status-im/nim-waku/vendor/nim-bearssl/bearssl/csources/src/ssl/ssl_engine.c:876
#12 br_ssl_engine_sendapp_ack (cc=0x7fb967ac2ed0, len=<optimized out>)
    at /mnt/c/source/status-im/nim-waku/vendor/nim-bearssl/bearssl/csources/src/ssl/ssl_engine.c:1133
#13 0x0000558a6cd0b8c6 in tlsWriteApp__phCXD6wg7ckL8oVNweWyWw_2 (chronosInternalRetFuture=<optimized out>, ClE_0=<optimized out>)
    at /mnt/c/source/status-im/nim-waku/vendor/nim-chronos/chronos/streams/tlsstream.nim:179
#14 0x0000558a6cb05ebb in futureContinue__qIqBDJYEJWZtFBnGxe9aPog (fut=<optimized out>)
    at /mnt/c/source/status-im/nim-waku/vendor/nim-chronos/chronos/asyncfutures2.nim:365
#15 0x0000558a6cb128cd in poll__YNjd8fE6xG8CRNwfLnrx0g_2 ()
    at /mnt/c/source/status-im/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/deques.nim:390
#16 0x0000558a6cb22255 in runForever__YNjd8fE6xG8CRNwfLnrx0g_3 () at /mnt/c/source/status-im/nim-waku/vendor/nim-chronos/chronos/asyncloop.nim:1085
#17 0x0000558a6cee172e in NimMainModule () at /mnt/c/source/status-im/nim-waku/waku/v2/node/wakunode2.nim:1388
#18 0x0000558a6cee7816 in NimMain () at /mnt/c/source/status-im/nim-waku/vendor/dnsclient.nim/src/dnsclientpkg/types.nim:402
#19 0x0000558a6c8d67f1 in main (argc=<optimized out>, args=<optimized out>, env=<optimized out>)
    at /mnt/c/source/status-im/nim-waku/vendor/dnsclient.nim/src/dnsclientpkg/types.nim:409
```

the version was eb02e4411b2f84cca162153c7d721e04e6432cb9

The core is 124mb; let me know if attaching that would be helpful.

**Comment by jm-clius** [comment]
Closing issue, as the issue has been open for a while and we haven't been able to reproduce it internally yet. If it occurs again, feel free to reopen. With the upcoming [Waku operator trial](https://github.com/vacp2p/research/issues/133) monitoring for unexpected bugs (e.g. segfaults) will be significantly expanded.
